import type { Action, GameEvent, GameState } from '../../state/GameState';
import type { RuleActionAdapter } from '../RuleAdapter';
import type { ActionValidationResult } from '../ActionResolver';
import type { ActionTypeHandler, NormalizedActionResult } from './contracts';
import { findActorUnit, hasLineOfSight, hasSpatialPosition, isOutOfRange } from './spatialTargetChecksStage';
import { buildResourcePaymentEvents } from './resourcePaymentStage';
import { buildActionEmissionEvents } from './eventEmissionStage';
import {
  toApplyStatusCandidatePayload,toAttackCandidatePayload,toEndCommandCandidatePayload,toMoveCandidatePayload,toPassCandidatePayload,toUseAbilityCandidatePayload,toUseItemCandidatePayload,
  toRecord,validateAllowedKeys,APPLY_STATUS_PAYLOAD_KEYS,ATTACK_PAYLOAD_KEYS,END_COMMAND_PAYLOAD_KEYS,MOVE_PAYLOAD_KEYS,PASS_PAYLOAD_KEYS,USE_ABILITY_PAYLOAD_KEYS,USE_ITEM_PAYLOAD_KEYS,
} from './payloadSchemaValidationStage';
import { matchesApplyStatusLegalAction,matchesAttackLegalAction,matchesEndCommandLegalAction,matchesMoveLegalAction,matchesPassLegalAction,matchesUseAbilityLegalAction,matchesUseItemLegalAction } from './legalActionMatchingStage';

function invalid(reason:string,details?:Record<string,string|number|boolean>):ActionValidationResult{return {isValid:false,reason,details};}

export function createActionHandlers(ruleAdapter?: RuleActionAdapter): Record<Action['type'], ActionTypeHandler> {
  return {
    ATTACK: {
      type:'ATTACK',
      validate(state, action, legal){ if(legal.length===0) return invalid('ATTACK_NOT_LEGAL_IN_PHASE',{phase:state.phase}); const p=toRecord(action.payload); if(!p) return invalid('INVALID_ATTACK_PAYLOAD_TYPE',{expected:'object'}); const k=validateAllowedKeys(p,ATTACK_PAYLOAD_KEYS); if(!k.isValid) return k; const n=toAttackCandidatePayload(action.payload); if(!n) return invalid('ATTACK_AMOUNT_INVALID',{amount:String(p.amount)}); if(!matchesAttackLegalAction(action,legal,n)) return invalid('ATTACK_NOT_FOUND_IN_LEGAL_ACTIONS',{actorId:action.actorId,targetId:n.targetId}); const t=state.units[n.targetId]; if(!t||t.hp<=0) return invalid('ATTACK_TARGET_NOT_ALIVE',{targetId:n.targetId}); const a=findActorUnit(state,action.actorId); if(!a) return invalid('ATTACK_SOURCE_NOT_FOUND',{actorId:action.actorId}); if(!hasSpatialPosition(a)) return invalid('MISSING_SOURCE_POSITION',{actorId:action.actorId,sourceUnitId:a.id,actionType:action.type}); if(!hasSpatialPosition(t)) return invalid('MISSING_TARGET_POSITION',{actorId:action.actorId,targetId:n.targetId,actionType:action.type}); if(isOutOfRange(a,t,action)) return invalid('ATTACK_TARGET_OUT_OF_RANGE',{actorId:action.actorId,targetId:n.targetId}); if(!hasLineOfSight(state,a,t)) return invalid('ATTACK_TARGET_NO_LINE_OF_SIGHT',{actorId:action.actorId,targetId:n.targetId}); return {isValid:true}; },
      normalize(state, action){ const p=toAttackCandidatePayload(action.payload); const actorUnit=findActorUnit(state,action.actorId); return {action,actorUnit,targetUnit:p?state.units[p.targetId]:undefined}; },
      buildEffects(state, normalized){ const p=toAttackCandidatePayload(normalized.action.payload); const a=normalized.actorUnit; const t=normalized.targetUnit; if(!p||!a||!t) return []; const rr=ruleAdapter?.resolveAttack(state, normalized.action, a, t); const amount=rr?.amount ?? p.amount; const events:GameEvent[]=[{kind:'UNIT_DAMAGED',sourceId:a.ownerId,sourceUnitId:a.id,targetId:t.id,amount,abilityId:rr?.abilityId,turn:state.turn,round:state.round}]; for (const app of rr?.appliedStatusApplications ?? []) { for (let i=0;i<app.stacks;i+=1){ events.push({kind:'STATUS_APPLIED',sourceUnitId:a.id,targetId:t.id,statusId:app.statusId,duration:app.duration,turn:state.turn,round:state.round}); }} if ((rr?.appliedCooldownTurns ?? 0)>0 && rr?.abilityId){ const from=a.cooldowns?.[rr.abilityId] ?? 0; events.push({kind:'COOLDOWN_TICKED',unitId:a.id,abilityId:rr.abilityId,from,to:rr.appliedCooldownTurns ?? 0,turn:state.turn,round:state.round}); } if(rr?.defeated ?? t.hp-amount<=0){events.push({kind:'UNIT_DEFEATED',sourceId:a.ownerId,sourceUnitId:a.id,targetId:t.id,turn:state.turn,round:state.round});} return events; }
    },
    MOVE: { type:'MOVE', validate(state,action,legal){ const p=toRecord(action.payload); if(!p) return invalid('INVALID_MOVE_PAYLOAD_TYPE'); const k=validateAllowedKeys(p,MOVE_PAYLOAD_KEYS); if(!k.isValid) return k; const n=toMoveCandidatePayload(action.payload); if(!n){ if(p.to===undefined) return invalid('MISSING_TARGET_POSITION',{actorId:action.actorId,actionType:action.type}); return invalid('MOVE_PAYLOAD_INVALID'); } const s=state.units[n.unitId]; if(!s||!s.position) return invalid('MISSING_SOURCE_POSITION',{actorId:action.actorId,sourceUnitId:n.unitId,actionType:action.type}); if(s.position.x===n.to.x&&s.position.y===n.to.y) return invalid('MOVE_DESTINATION_UNCHANGED'); const occ=Object.values(state.units).some(c=>c.id!==s.id&&c.hp>0&&c.position?.x===n.to.x&&c.position?.y===n.to.y); if(occ) return invalid('MOVE_DESTINATION_OCCUPIED',{actorId:action.actorId,unitId:n.unitId,x:n.to.x,y:n.to.y}); if(legal.length===0) return invalid('MOVE_NOT_LEGAL_IN_PHASE'); return matchesMoveLegalAction(action,legal,n)?{isValid:true}:invalid('MOVE_NOT_FOUND_IN_LEGAL_ACTIONS'); }, normalize(state,action){ return {action,actorUnit:findActorUnit(state,action.actorId)}; }, buildEffects(){ return []; } },
    USE_ABILITY:{ type:'USE_ABILITY', validate(state,action,legal){ const p=toRecord(action.payload); if(!p) return invalid('INVALID_USE_ABILITY_PAYLOAD_TYPE'); const k=validateAllowedKeys(p,USE_ABILITY_PAYLOAD_KEYS); if(!k.isValid) return k; const n=toUseAbilityCandidatePayload(action.payload); if(!n) return invalid('USE_ABILITY_PAYLOAD_INVALID'); const s=state.units[n.unitId]; if(!s||!hasSpatialPosition(s)) return invalid('MISSING_SOURCE_POSITION',{actorId:action.actorId,sourceUnitId:n.unitId,actionType:action.type}); if(n.targetId){const t=state.units[n.targetId]; if(!t||!hasSpatialPosition(t)) return invalid('MISSING_TARGET_POSITION',{actorId:action.actorId,targetId:n.targetId,actionType:action.type});} if(legal.length===0) return invalid('USE_ABILITY_NOT_LEGAL_IN_PHASE'); return matchesUseAbilityLegalAction(action,legal,n)?{isValid:true}:invalid('USE_ABILITY_NOT_FOUND_IN_LEGAL_ACTIONS'); }, normalize(state,action){ const n=toUseAbilityCandidatePayload(action.payload); return {action,actorUnit:findActorUnit(state,action.actorId),targetUnit:n?.targetId?state.units[n.targetId]:undefined};},buildEffects(){return [];} },
    USE_ITEM:{ type:'USE_ITEM', validate(_s,action,legal){ if(legal.length===0) return invalid('USE_ITEM_NOT_LEGAL_IN_PHASE'); const p=toRecord(action.payload); if(!p) return invalid('INVALID_USE_ITEM_PAYLOAD_TYPE'); const k=validateAllowedKeys(p,USE_ITEM_PAYLOAD_KEYS); if(!k.isValid) return k; const n=toUseItemCandidatePayload(action.payload); if(!n) return invalid('USE_ITEM_PAYLOAD_INVALID'); return matchesUseItemLegalAction(action,legal,n)?{isValid:true}:invalid('USE_ITEM_NOT_FOUND_IN_LEGAL_ACTIONS');}, normalize(state,action){ const n=toUseItemCandidatePayload(action.payload); return {action,actorUnit:findActorUnit(state,action.actorId),targetUnit:n?.targetId?state.units[n.targetId]:undefined};}, buildEffects(){return [];} },
    APPLY_STATUS:{ type:'APPLY_STATUS', validate(state,action,legal){ if(legal.length===0) return invalid('APPLY_STATUS_NOT_LEGAL_IN_PHASE'); const p=toRecord(action.payload); if(!p) return invalid('INVALID_APPLY_STATUS_PAYLOAD_TYPE'); const k=validateAllowedKeys(p,APPLY_STATUS_PAYLOAD_KEYS); if(!k.isValid) return k; const n=toApplyStatusCandidatePayload(action.payload); if(!n) return invalid('APPLY_STATUS_PAYLOAD_INVALID'); const t=state.units[n.targetId]; if(!t||t.hp<=0) return invalid('APPLY_STATUS_TARGET_NOT_ALIVE',{targetId:n.targetId}); return matchesApplyStatusLegalAction(action,legal,n)?{isValid:true}:invalid('APPLY_STATUS_NOT_FOUND_IN_LEGAL_ACTIONS'); }, normalize(state,action){ const p=toApplyStatusCandidatePayload(action.payload); return {action,actorUnit:findActorUnit(state,action.actorId),targetUnit:p?state.units[p.targetId]:undefined}; }, buildEffects(state,n){ const p=toApplyStatusCandidatePayload(n.action.payload); if(!p) return []; return [{kind:'STATUS_APPLIED',sourceUnitId:p.sourceUnitId,targetId:p.targetId,statusId:p.statusId,duration:p.duration,turn:state.turn,round:state.round}]; } },
    END_COMMAND:{ type:'END_COMMAND', validate(_s,a,l){ if(l.length===0) return invalid('END_COMMAND_NOT_LEGAL_IN_PHASE'); const n=toEndCommandCandidatePayload(a.payload); if(!n) return invalid('END_COMMAND_REASON_INVALID',{reason:String((toRecord(a.payload)?.reason))}); return matchesEndCommandLegalAction(a,l,n)?{isValid:true}:invalid('END_COMMAND_NOT_FOUND_IN_LEGAL_ACTIONS',{actorId:a.actorId}); }, normalize(_s,a){ return {action:a}; }, buildEffects(){return [];} },
    PASS:{ type:'PASS', validate(_s,a,l){ if(l.length===0) return invalid('PASS_NOT_LEGAL_IN_PHASE'); const n=toPassCandidatePayload(a.payload); if(!n) return invalid('PASS_PHASE_REQUIRED'); return matchesPassLegalAction(a,l,n)?{isValid:true}:invalid('PASS_NOT_FOUND_IN_LEGAL_ACTIONS',{actorId:a.actorId,phase:n.phase}); }, normalize(_s,a){ return {action:a}; }, buildEffects(){return [];} },
  };
}

export const defaultResourceStage = { build: buildResourcePaymentEvents };
export const defaultEventAssemblyStage = { build: buildActionEmissionEvents };
